name: build artifacts

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build artifacts
        run: ./build-artifacts.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/*
          if-no-files-found: error
